platform :ios, '9.0'
use_frameworks!

target 'LXMDownloader_Example' do
  pod 'LXMDownloader', :path => '../'

  pod 'LXMBlockKit'
  pod 'LXMPlayer', :git => 'https://github.com/Phelthas/LXMPlayer'
end
